import type { ProcessDefinition } from './types';
import { EVENT_SIZE, GATEWAY_SIZE, TASK_SIZE } from './nodeSizes';

export const criticalUpdateReleaseProcess: ProcessDefinition = {
  id: 'critical_update_release',
  title: 'Разработка и релиз критического обновления ПО',
  pool: {
    id: 'enterprise_sdlc',
    label: 'Enterprise SDLC',
  },
  lanes: [
    { id: 'product_owner', label: 'Product Owner' },
    { id: 'architect', label: 'Архитектор' },
    { id: 'backend', label: 'Backend-разработчик' },
    { id: 'frontend', label: 'Frontend-разработчик' },
    { id: 'qa', label: 'QA-инженер' },
    { id: 'security', label: 'Security Officer' },
    { id: 'devops', label: 'DevOps-инженер' },
  ],
  nodes: [
    { id: 'start', type: 'startEvent', label: 'Start', lane: 'product_owner', size: EVENT_SIZE },
    { id: 'create_story', type: 'task', label: 'Создать User Story в Jira', lane: 'product_owner', size: TASK_SIZE },
    { id: 'design_solution', type: 'task', label: 'Спроектировать техническое решение', lane: 'architect', size: TASK_SIZE },
    { id: 'architecture_decision', type: 'exclusiveGateway', label: 'Реализация согласована?', lane: 'architect', size: GATEWAY_SIZE },
    { id: 'reject_story', type: 'task', label: 'Отклонить задачу', lane: 'product_owner', size: TASK_SIZE },
    { id: 'end_rejected', type: 'endEvent', label: 'End', lane: 'product_owner', size: EVENT_SIZE },

    { id: 'development_fork', type: 'parallelGateway', label: 'Запустить backend и frontend', lane: 'architect', size: GATEWAY_SIZE },

    { id: 'backend_api', type: 'task', label: 'Разработать API', lane: 'backend', size: TASK_SIZE },
    { id: 'backend_unit', type: 'task', label: 'Покрыть код Unit-тестами', lane: 'backend', size: TASK_SIZE },
    { id: 'backend_mr', type: 'task', label: 'Создать Merge Request', lane: 'backend', size: TASK_SIZE },
    { id: 'backend_tests', type: 'task', label: 'Прогнать Jenkins-проверки', lane: 'backend', size: TASK_SIZE },
    { id: 'backend_review', type: 'task', label: 'Провести Backend Code Review', lane: 'architect', size: TASK_SIZE },
    { id: 'backend_done', type: 'task', label: 'Смерджить backend в develop', lane: 'backend', size: TASK_SIZE },

    { id: 'frontend_ui', type: 'task', label: 'Разработать UI и клиентский код', lane: 'frontend', size: TASK_SIZE },
    { id: 'frontend_layout', type: 'task', label: 'Сверстать UI-компоненты', lane: 'frontend', size: TASK_SIZE },
    { id: 'frontend_mr', type: 'task', label: 'Создать Merge Request', lane: 'frontend', size: TASK_SIZE },
    { id: 'frontend_review', type: 'task', label: 'Провести Frontend Code Review', lane: 'architect', size: TASK_SIZE },
    { id: 'frontend_done', type: 'task', label: 'Смерджить frontend в develop', lane: 'frontend', size: TASK_SIZE },

    { id: 'development_join', type: 'parallelGateway', label: 'Обе ветки готовы', lane: 'devops', size: GATEWAY_SIZE },
    { id: 'deploy_staging', type: 'task', label: 'Деплой на Staging', lane: 'devops', size: TASK_SIZE },

    { id: 'validation_fork', type: 'parallelGateway', label: 'Запустить QA и Security', lane: 'devops', size: GATEWAY_SIZE },
    { id: 'qa_validation', type: 'task', label: 'Протестировать релиз', lane: 'qa', size: TASK_SIZE },
    { id: 'security_scan', type: 'task', label: 'Просканировать уязвимости', lane: 'security', size: TASK_SIZE },
    { id: 'validation_join', type: 'parallelGateway', label: 'Результаты получены', lane: 'devops', size: GATEWAY_SIZE },
    { id: 'validation_decision', type: 'exclusiveGateway', label: 'Есть критические проблемы?', lane: 'devops', size: GATEWAY_SIZE },

    { id: 'deploy_production', type: 'task', label: 'Деплой на Production', lane: 'devops', size: TASK_SIZE },
    { id: 'setup_alerts', type: 'task', label: 'Настроить алерты мониторинга', lane: 'devops', size: TASK_SIZE },
    { id: 'smoke_period', type: 'task', label: 'Наблюдать 1 час за метриками', lane: 'devops', size: TASK_SIZE },
    { id: 'release_decision', type: 'exclusiveGateway', label: 'Релиз стабилен?', lane: 'devops', size: GATEWAY_SIZE },
    { id: 'close_story', type: 'task', label: 'Закрыть задачу в Jira', lane: 'product_owner', size: TASK_SIZE },
    { id: 'end_success', type: 'endEvent', label: 'End', lane: 'product_owner', size: EVENT_SIZE },
    { id: 'rollback', type: 'task', label: 'Откатить версию', lane: 'devops', size: TASK_SIZE },
    { id: 'handoff_logs', type: 'task', label: 'Передать логи разработчикам', lane: 'devops', size: TASK_SIZE },
    { id: 'hotfix_target', type: 'exclusiveGateway', label: 'Где исправлять?', lane: 'devops', size: GATEWAY_SIZE },
  ],
  edges: [
    { id: 'e1', source: 'start', target: 'create_story', kind: 'forward' },
    { id: 'e2', source: 'create_story', target: 'design_solution', kind: 'forward' },
    { id: 'e3', source: 'design_solution', target: 'architecture_decision', kind: 'forward' },
    { id: 'e4', source: 'architecture_decision', target: 'reject_story', label: 'Нет', kind: 'forward' },
    { id: 'e5', source: 'reject_story', target: 'end_rejected', kind: 'forward' },
    { id: 'e6', source: 'architecture_decision', target: 'development_fork', label: 'Да', kind: 'forward' },

    { id: 'e7', source: 'development_fork', target: 'backend_api', kind: 'forward' },
    { id: 'e8', source: 'backend_api', target: 'backend_unit', kind: 'forward' },
    { id: 'e9', source: 'backend_unit', target: 'backend_mr', kind: 'forward' },
    { id: 'e10', source: 'backend_mr', target: 'backend_tests', kind: 'forward' },
    { id: 'e11', source: 'backend_tests', target: 'backend_review', label: 'Тесты OK', kind: 'forward' },
    { id: 'e12', source: 'backend_review', target: 'backend_done', label: 'Approve', kind: 'forward' },
    { id: 'e13', source: 'backend_done', target: 'development_join', kind: 'forward' },

    { id: 'e14', source: 'development_fork', target: 'frontend_ui', kind: 'forward' },
    { id: 'e15', source: 'frontend_ui', target: 'frontend_layout', kind: 'forward' },
    { id: 'e16', source: 'frontend_layout', target: 'frontend_mr', kind: 'forward' },
    { id: 'e17', source: 'frontend_mr', target: 'frontend_review', kind: 'forward' },
    { id: 'e18', source: 'frontend_review', target: 'frontend_done', label: 'Approve', kind: 'forward' },
    { id: 'e19', source: 'frontend_done', target: 'development_join', kind: 'forward' },

    { id: 'e20', source: 'development_join', target: 'deploy_staging', kind: 'forward' },
    { id: 'e21', source: 'deploy_staging', target: 'validation_fork', kind: 'forward' },
    { id: 'e22', source: 'validation_fork', target: 'qa_validation', kind: 'forward' },
    { id: 'e23', source: 'validation_fork', target: 'security_scan', kind: 'forward' },
    { id: 'e24', source: 'qa_validation', target: 'validation_join', kind: 'forward' },
    { id: 'e25', source: 'security_scan', target: 'validation_join', kind: 'forward' },
    { id: 'e26', source: 'validation_join', target: 'validation_decision', kind: 'forward' },
    { id: 'e27', source: 'validation_decision', target: 'deploy_production', label: 'Успех', kind: 'forward' },

    { id: 'e28', source: 'deploy_production', target: 'setup_alerts', kind: 'forward' },
    { id: 'e29', source: 'setup_alerts', target: 'smoke_period', kind: 'forward' },
    { id: 'e30', source: 'smoke_period', target: 'release_decision', kind: 'forward' },
    { id: 'e31', source: 'release_decision', target: 'close_story', label: 'Стабильно', kind: 'forward' },
    { id: 'e32', source: 'close_story', target: 'end_success', kind: 'forward' },
    { id: 'e33', source: 'release_decision', target: 'rollback', label: 'Сбой', kind: 'forward' },
    { id: 'e34', source: 'rollback', target: 'handoff_logs', kind: 'forward' },
    { id: 'e35', source: 'handoff_logs', target: 'hotfix_target', kind: 'forward' },

    { id: 'e36', source: 'backend_tests', target: 'backend_api', label: 'Тесты не пройдены', kind: 'backward' },
    { id: 'e37', source: 'backend_review', target: 'backend_api', label: 'Есть замечания', kind: 'backward' },
    { id: 'e38', source: 'frontend_review', target: 'frontend_ui', label: 'Есть замечания', kind: 'backward' },
    { id: 'e39', source: 'validation_decision', target: 'backend_api', label: 'Баг в API', kind: 'backward' },
    { id: 'e40', source: 'validation_decision', target: 'frontend_ui', label: 'Баг в UI', kind: 'backward' },
    { id: 'e41', source: 'validation_decision', target: 'design_solution', label: 'Проблема архитектуры', kind: 'backward' },
    { id: 'e42', source: 'hotfix_target', target: 'backend_api', label: 'Backend', kind: 'backward' },
    { id: 'e43', source: 'hotfix_target', target: 'frontend_ui', label: 'Frontend', kind: 'backward' },
  ],
};