import type { ProcessDefinition } from './types';

const TASK_SIZE = { width: 100, height: 80 };
const EVENT_SIZE = { width: 36, height: 36 };
const GATEWAY_SIZE = { width: 50, height: 50 };

export const serviceRolloutProcess: ProcessDefinition = {
  id: 'service_rollout',
  title: 'Разворачивание и настройка нового корпоративного ИТ-сервиса',
  pool: {
    id: 'deployment_process',
    label: 'Deployment Process',
  },
  lanes: [
    { id: 'manager', label: 'Менеджер проекта' },
    { id: 'devops', label: 'DevOps-инженер' },
    { id: 'dba', label: 'Администратор БД' },
    { id: 'security', label: 'Инженер по безопасности' },
  ],
  nodes: [
    { id: 'start', type: 'startEvent', label: 'Start', lane: 'manager', size: EVENT_SIZE },
    { id: 'create_ticket', type: 'task', label: 'Создать задачу в Jira', lane: 'manager', size: TASK_SIZE },
    { id: 'accept_service', type: 'task', label: 'Проверить корректность работы сервиса', lane: 'manager', size: TASK_SIZE },
    { id: 'handoff_access', type: 'task', label: 'Передать доступы пользователям', lane: 'manager', size: TASK_SIZE },
    { id: 'close_ticket', type: 'task', label: 'Закрыть задачу в Jira', lane: 'manager', size: TASK_SIZE },
    { id: 'end', type: 'endEvent', label: 'End', lane: 'manager', size: EVENT_SIZE },
    { id: 'analyze_infra', type: 'task', label: 'Проанализировать требования к ресурсам', lane: 'devops', size: TASK_SIZE },
    { id: 'infra_type', type: 'exclusiveGateway', label: 'Требуются облачные ресурсы?', lane: 'devops', size: GATEWAY_SIZE },
    { id: 'provision_cloud', type: 'task', label: 'Заказать облачные ресурсы через Terraform', lane: 'devops', size: TASK_SIZE },
    { id: 'provision_onprem', type: 'task', label: 'Выделить локальный сервер и настроить ОС через Ansible', lane: 'devops', size: TASK_SIZE },
    { id: 'configure_env', type: 'task', label: 'Сконфигурировать окружение в Ansible', lane: 'devops', size: TASK_SIZE },
    { id: 'devops_done', type: 'task', label: 'Поставить статус "Готово" в Jira', lane: 'devops', size: TASK_SIZE },
    { id: 'review_db_requirements', type: 'task', label: 'Получить требования', lane: 'dba', size: TASK_SIZE },
    { id: 'create_db', type: 'task', label: 'Создать экземпляр БД в СУБД', lane: 'dba', size: TASK_SIZE },
    { id: 'setup_schema', type: 'task', label: 'Настроить схемы и миграции', lane: 'dba', size: TASK_SIZE },
    { id: 'configure_access', type: 'task', label: 'Сконфигурировать доступы', lane: 'dba', size: TASK_SIZE },
    { id: 'dba_done', type: 'task', label: 'Поставить статус "Готово" в Jira', lane: 'dba', size: TASK_SIZE },
    { id: 'prep_fork', type: 'parallelGateway', label: 'Запустить подготовку', lane: 'security', size: GATEWAY_SIZE },
    { id: 'prep_join', type: 'parallelGateway', label: 'Подготовка завершена', lane: 'security', size: GATEWAY_SIZE },
    { id: 'run_scan', type: 'task', label: 'Запустить сканирование в SonarQube', lane: 'security', size: TASK_SIZE },
    { id: 'review_scan', type: 'task', label: 'Проанализировать отчет', lane: 'security', size: TASK_SIZE },
    { id: 'security_decision', type: 'exclusiveGateway', label: 'Есть критические уязвимости?', lane: 'security', size: GATEWAY_SIZE },
    { id: 'issue_class', type: 'exclusiveGateway', label: 'Класс проблемы?', lane: 'security', size: GATEWAY_SIZE },
    { id: 'signoff', type: 'task', label: 'Подписать акт соответствия', lane: 'security', size: TASK_SIZE },
  ],
  edges: [
    { id: 'e1', source: 'start', target: 'create_ticket', kind: 'forward' },
    { id: 'e2', source: 'create_ticket', target: 'prep_fork', kind: 'forward' },
    { id: 'e3', source: 'prep_fork', target: 'analyze_infra', kind: 'forward' },
    { id: 'e4', source: 'analyze_infra', target: 'infra_type', kind: 'forward' },
    { id: 'e5', source: 'infra_type', target: 'provision_cloud', label: 'Cloud', kind: 'forward' },
    { id: 'e6', source: 'infra_type', target: 'provision_onprem', label: 'On-Prem', kind: 'forward' },
    { id: 'e7', source: 'provision_cloud', target: 'configure_env', kind: 'forward' },
    { id: 'e8', source: 'provision_onprem', target: 'configure_env', kind: 'forward' },
    { id: 'e9', source: 'configure_env', target: 'devops_done', kind: 'forward' },
    { id: 'e10', source: 'devops_done', target: 'prep_join', kind: 'forward' },
    { id: 'e11', source: 'prep_fork', target: 'review_db_requirements', kind: 'forward' },
    { id: 'e12', source: 'review_db_requirements', target: 'create_db', kind: 'forward' },
    { id: 'e13', source: 'create_db', target: 'setup_schema', kind: 'forward' },
    { id: 'e14', source: 'setup_schema', target: 'configure_access', kind: 'forward' },
    { id: 'e15', source: 'configure_access', target: 'dba_done', kind: 'forward' },
    { id: 'e16', source: 'dba_done', target: 'prep_join', kind: 'forward' },
    { id: 'e17', source: 'prep_join', target: 'run_scan', kind: 'forward' },
    { id: 'e18', source: 'run_scan', target: 'review_scan', kind: 'forward' },
    { id: 'e19', source: 'review_scan', target: 'security_decision', kind: 'forward' },
    { id: 'e20', source: 'security_decision', target: 'signoff', label: 'Успех', kind: 'forward' },
    { id: 'e21', source: 'security_decision', target: 'issue_class', label: 'Найдены проблемы', kind: 'forward' },
    { id: 'e22', source: 'issue_class', target: 'configure_env', label: 'Ошибки сервера', kind: 'backward' },
    { id: 'e23', source: 'issue_class', target: 'configure_access', label: 'Ошибки доступа', kind: 'backward' },
    { id: 'e24', source: 'signoff', target: 'accept_service', kind: 'forward' },
    { id: 'e25', source: 'accept_service', target: 'handoff_access', kind: 'forward' },
    { id: 'e26', source: 'handoff_access', target: 'close_ticket', kind: 'forward' },
    { id: 'e27', source: 'close_ticket', target: 'end', kind: 'forward' },
  ],
};